import {StyleSheet} from 'react-native';
import { colors } from '../../../styles';

export const styles = StyleSheet.create({
  modalBackground: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: 'white',
    paddingBottom: 15,
    borderTopRightRadius: 8,
    borderTopLeftRadius: 8,
    alignItems: 'center',
    width: '100%',
    maxHeight: '80%',
  },
  textStyle: {
    color: 'black',
    textAlign: 'left',
  },
  modalTitle: {
    fontSize: 20,
    padding: 10,
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  modalText: {
    marginBottom: 16,
    textAlign: 'left',
  },
  title: {
    backgroundColor: colors.arcGreen,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    borderTopRightRadius: 8,
    borderTopLeftRadius: 8,
  },
  labelContainer: {flexDirection: 'row', alignItems: 'center', padding: 15},
  inputHost: {
    borderColor: 'black',
    color: 'black',
    borderWidth: 1,
    width: '85%',
    borderRadius: 8,
    padding: 5,
    fontSize: 18,
    height: 40,
  },
  inputStore: {
    borderColor: 'black',
    color: 'black',
    borderWidth: 1,
    width: '74%',
    borderRadius: 8,
    padding: 5,
    fontSize: 18,
    height: 40,
  },
  inputTerminal: {
    borderColor: 'black',
    color: 'black',
    borderWidth: 1,
    width: '75%',
    height: 40,
    borderRadius: 8,
    padding: 5,
    fontSize: 18,
  },
  label: {marginRight: 10, color: 'black', fontSize: 18, fontWeight: 'bold'},
  buttonContainer: {
    width: '90%',
    alignItems: 'center',
    backgroundColor: colors.arcGreen,
    paddingVertical: 5,
    paddingHorizontal: 20,
    marginVertical: 5,
    borderRadius: 15,
  },
  buttonLabel: {color: 'white', fontSize: 16},
});
